#!/bin/bash

DMENU="rofi -dmenu"
match=$(printf "shutdown\\nreboot\\ntimed shutdown\\ncancel shutdown" | $DMENU)

case "$match" in
"shutdown")
    ok=$(printf "yes\\nno" | $DMENU -p "realy?")
    if [ "$ok" == "yes" ]
    then
        shutdown now
    else
        notify-send "dont waste my time"
    fi
    ;;
"reboot")
    ok=$(printf "yes\\nno" | $DMENU -p "realy?")
    if [ "$ok" == "yes" ]
    then
        reboot
    else
        notify-send "dont waste my time"
    fi
    ;;
"timed shutdown")
    min=$($DMENU -p "in how much minutes?")
    output=$(shutdown -P +"$min" 2>&1 &)
    notify-send "$output"
    ;;
"cancel shutdown")
    output=$(shutdown -c 2>&1 &)
    notify-send "shutdown canceled"
    ;;
*)
    notify-send "dont waste my time"
    ;;
esac
