#!/bin/bash
# sr -elvi >> list of all possible engines
engines="google;duckduckgo;aur;youtube;commandlinefu;archwiki"
choice=$(echo -e "${engines//;/\\n}" | rofi -dmenu -p "engine")
query=$(rofi -dmenu -p "websearch")
sr -browser="$BROWSER" "$choice" "$query"
