#!/bin/bash
choice=$(sed '/^$/d;/^#/d;/^\//d' ~/.config/surfraw/bookmarks | rofi -dmenu -mesg ">>> config:~/.config/surfraw/bookmarks" -i -p "bookmarks: ")

query=""
#ask for query if bookmark contains a %s
if [[ $choice == *"%s"* ]]; then
    query=$(rofi -dmenu -p "search")
fi

#open bookmark
sr -browser="$BROWSER" "$choice" "$query"
