#!/bin/bash
DMENU="rofi -dmenu"
dest="/home/ljurk/.config/i3blocks/scripts/.timerfile"

unit=$(printf "ü\\nÜ\\nä\\nÄ\\nö\\nÖ\\nß" | $DMENU "which one?")
echo -n "$unit" | xclip -selection c
notify-send "'$unit' copied to clipboard"
